### ISSUE TITLE
Question about VAEPolicy in rlkit.torch.sac.policies

### ISSUE THREAD

**Issue by HYDesmondLiu** [rail-berkeley/rlkit#158]
In [UWAC paper](https://scholar.google.com/scholar_url?url=https://arxiv.org/abs/2105.08140&hl=en&sa=T&oi=gsb&ct=res&cd=0&d=4444134390271190858&ei=Uh2EYYH1HumGy9YPp5i9oAM&scisig=AAGBfm22dRgGHn7Ax5_XjCEdSmae01DiAg), they did `from rlkit.torch.sac.policies import TanhGaussianPolicy, MakeDeterministic, VAEPolicy` in `examples/UWAC_hdf5_d4rl.py`.

However, even in rlkit repository there is no such class. May I know where can I get the latest version of the repository?

**Comment by anair13** [comment]
Yes, it looks like it is probably based off of this repo: https://github.com/rail-berkeley/d4rl_evaluations/blob/master/bear/rlkit/torch/sac/policies.py

**Comment by HYDesmondLiu** [comment]
Thank you @anair13 for the pointer, now it makes sense.
