### ISSUE TITLE
CustomMDPPathCollector is not found

### ISSUE THREAD

**Issue by Shinntarou** [rail-berkeley/rlkit#159]
I wont to run CQL/d4rl/example/cql_mujoco_new.py
but I got this error

ImportError: cannot import name 'CustomMDPPathCollector' from 'rlkit.samplers.data_collector.path_collector' (/home/usr/rlkit-master/rlkit/samplers/data_collector/path_collector.py)

teach me please where is CustomMDPPathCollector path

**Comment by anair13** [comment]
You should use the rlkit version included in the CQL repo: https://github.com/aviralkumar2907/CQL/tree/master/d4rl/rlkit

**Comment by Shinntarou** [comment]
thankyou
