### ISSUE TITLE
Python3.5 is not suitable for this project!

### ISSUE THREAD

**Issue by ZhenhuiTang** [rail-berkeley/rlkit#169]
I follow the environment.yml to install packages, include python3.5

Then I need to install mujoco1.5

Then I need to install mujoco_py 1.5

However, it need to install pillow=8.2.0, which only be supported by python3.7+

I was wandering how they works on mujoco 1.5. with the environment.yml.

**Comment by siyamsajeebkhan** [comment]
Hi @ZhenhuiTang ,
I am also facing a similar issue. How did you solve it?
