### ISSUE TITLE
Download link is expired

### ISSUE THREAD

**Issue by deepneuralnetworks** [rail-berkeley/rlkit#174]
Hello. Thank you for the great work.

I found that the download links below are expired.

Can update the links please?

MuJoCo benchmark tasks - [https://drive.google.com/file/d/1edcuicVv2d-PqH1aZUVbO5CeRq3lqK89/view](https://drive.google.com/file/d/1edcuicVv2d-PqH1aZUVbO5CeRq3lqK89/view)
Dexterous manipulation - [https://drive.google.com/file/d/1SsVaQKZnY5UkuR78WrInp9XxTdKHbF0x/view](https://drive.google.com/file/d/1SsVaQKZnY5UkuR78WrInp9XxTdKHbF0x/view)

Thank you.

**Comment by anair13** [comment]
Thanks for catching this! I've reshared the data and updated the links

**Comment by deepneuralnetworks** [comment]
Thank you for the fast reply. Closing the issue.
